Public Class ledReturn
    Public Function returnLED(code As Integer) As String
        If (code <= 32) Then
            Select Case code
                Case 0
                    Return "808080" 'Disable Color (Erase)
                Case 1
                    Return "DADFE4"
                Case 2
                    Return "E6E9ED"
                Case 3
                    Return "FAFAFA"
                Case 4
                    Return "F8BBD0"
                Case 5
                    Return "EF5350"
                Case 6
                    Return "E57373"
                Case 7
                    Return "EF9A9A"
                Case 8
                    Return "FFF3E0"
                Case 9
                    Return "FFA726"
                Case 10
                    Return "FFB960"
                Case 11
                    Return "FFCC80"
                Case 12
                    Return "FFE0B2"
                Case 13
                    Return "FFEE58"
                Case 14
                    Return "FFF59D"
                Case 15
                    Return "FFF9C4"
                Case 16
                    Return "DCEDC8"
                Case 17
                    Return "8BC34A"
                Case 18
                    Return "AED581"
                Case 19
                    Return "BFDF9F"
                Case 20
                    Return "5EE2B0"
                Case 21
                    Return "00CE3C"
                Case 22
                    Return "00BA43"
                Case 23
                    Return "119C3F"
                Case 24
                    Return "57ECC1"
                Case 25
                    Return "00E864"
                Case 26
                    Return "00E05C"
                Case 27
                    Return "00D545"
                Case 28
                    Return "7AFDDD"
                Case 29
                    Return "00E4C5"
                Case 30
                    Return "00E0B2"
                Case 31
                    Return "01EEC6"
                Case 32
                    Return "49EFEF"
            End Select
        ElseIf (code <= 64) Then
            Select Case code
                Case 33
                    Return "00E7D8"
                Case 34
                    Return "00E5D1"
                Case 35
                    Return "01EFDE"
                Case 36
                    Return "6ADDFF"
                Case 37
                    Return "00DAFE"
                Case 38
                    Return "01D6FF"
                Case 39
                    Return "08ACDC"
                Case 40
                    Return "73CEFE"
                Case 41
                    Return "0D9BF7"
                Case 42
                    Return "148DE4"
                Case 43
                    Return "2A77C9"
                Case 44
                    Return "8693FF"
                Case 45
                    Return "2196F3"
                Case 46
                    Return "4668F6"
                Case 47
                    Return "4153DC"
                Case 48
                    Return "B095FF"
                Case 49
                    Return "8453FD"
                Case 50
                    Return "634ACD"
                Case 51
                    Return "5749C5"
                Case 52
                    Return "FFB7FF"
                Case 53
                    Return "E863FB"
                Case 54
                    Return "D655ED"
                Case 55
                    Return "D14FE9"
                Case 56
                    Return "FC99E3"
                Case 57
                    Return "E736C2"
                Case 58
                    Return "E52FBE"
                Case 59
                    Return "E334B6"
                Case 60
                    Return "ED353E"
                Case 61
                    Return "FFA726"
                Case 62
                    Return "F4DF0B"
                Case 63
                    Return "66BB6A"
                Case 64
                    Return "5CD100"
            End Select
        ElseIf (code <= 96) Then
            Select Case code
                Case 65
                    Return "00D29E"
                Case 66
                    Return "2388FF"
                Case 67
                    Return "3669FD"
                Case 68
                    Return "00B4D0"
                Case 69
                    Return "475CDC"
                Case 70
                    Return "F2F3F5"
                Case 71
                    Return "EEF0F2"
                Case 72
                    Return "F72737"
                Case 73
                    Return "D2EA7B"
                Case 74
                    Return "C8DF10"
                Case 75
                    Return "7FE422"
                Case 76
                    Return "00C931"
                Case 77
                    Return "00D7A6"
                Case 78
                    Return "00D8FC"
                Case 79
                    Return "0B9BFC"
                Case 80
                    Return "585CF5"
                Case 81
                    Return "AC59F0"
                Case 82
                    Return "D980DC"
                Case 83
                    Return "B8814A"
                Case 84
                    Return "FF9800"
                Case 85
                    Return "ABDF22"
                Case 86
                    Return "9EE154"
                Case 87
                    Return "66BB6A"
                Case 88
                    Return "3BDA47"
                Case 89
                    Return "6FDEB9"
                Case 90
                    Return "27DBDA"
                Case 91
                    Return "9CC8FD"
                Case 92
                    Return "79B8F7"
                Case 93
                    Return "AFAFEF"
                Case 94
                    Return "D580EB"
                Case 95
                    Return "F74FCA"
                Case 96
                    Return "EA8A1F"
            End Select
        ElseIf (code <= 128) Then
            Select Case code
                Case 97
                    Return "DBDB08"
                Case 98
                    Return "9CD60D"
                Case 99
                    Return "F3D335"
                Case 100
                    Return "C8AF41"
                Case 101
                    Return "00CA69"
                Case 102
                    Return "24D2B0"
                Case 103
                    Return "757EBE"
                Case 104
                    Return "5388DB"
                Case 105
                    Return "E5C5A6"
                Case 106
                    Return "E93B3B"
                Case 107
                    Return "F9A2A1"
                Case 108
                    Return "ED9C65"
                Case 109
                    Return "E1CA72"
                Case 110
                    Return "B8DA78"
                Case 111
                    Return "98D52C"
                Case 112
                    Return "626CBD"
                Case 113
                    Return "CAC8A0"
                Case 114
                    Return "90D4C2"
                Case 115
                    Return "CEDDFE"
                Case 116
                    Return "BECCF7"
                Case 117
                    Return "D2D7DE"
                Case 118
                    Return "DADFE4"
                Case 119
                    Return "E6E9ED"
                Case 120
                    Return "FE1624"
                Case 121
                    Return "CD2724"
                Case 122
                    Return "9CCC65"
                Case 123
                    Return "009C1B"
                Case 124
                    Return "FFFF00"
                Case 125
                    Return "BEB212"
                Case 126
                    Return "F5D01D"
                Case 127
                    Return "E37829"
                Case 128
                    Return "5CD100"
            End Select
        End If
        Return "FFFFFF"
    End Function
End Class
